// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaotTrM-bNdzT0Y3vcNVR4wLaKw9JroKM',
    appId: '1:184370170004:web:f3f93a7348b09db2854c81',
    messagingSenderId: '184370170004',
    projectId: 'app-test-9c708',
    authDomain: 'app-test-9c708.firebaseapp.com',
    storageBucket: 'app-test-9c708.appspot.com',
    measurementId: 'G-7C0JKMJWKZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNKV1XY-jFQVxlD_eRghfzvR1J1IwJGUs',
    appId: '1:184370170004:android:6049e7a1de6f5c22854c81',
    messagingSenderId: '184370170004',
    projectId: 'app-test-9c708',
    storageBucket: 'app-test-9c708.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnTC1JhIf99LJDfGsrtbVZFDjRBpUcWBE',
    appId: '1:184370170004:ios:193339aa1ac59b59854c81',
    messagingSenderId: '184370170004',
    projectId: 'app-test-9c708',
    storageBucket: 'app-test-9c708.appspot.com',
    iosBundleId: 'com.example.demoProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnTC1JhIf99LJDfGsrtbVZFDjRBpUcWBE',
    appId: '1:184370170004:ios:6c7f67f8010f13ea854c81',
    messagingSenderId: '184370170004',
    projectId: 'app-test-9c708',
    storageBucket: 'app-test-9c708.appspot.com',
    iosBundleId: 'com.example.demoProject.RunnerTests',
  );
}
